### PR TITLE
Make library Ethernet compatible

### PR DESCRIPTION
**Pull request by BrenuDev**
Just by adding these checks the library works fine with the Ethernet interface.
It's not the perfect check but it's workable right now

### CODE REVIEW

**Comment by BrenuDev** [comment]
Added the header file

**Comment by mobizt** [comment]
Is it work with version 2.0 I recently update today?
I don't have hardware on hand to test.
If yes, I will merge the pull request.

**Comment by BrenuDev** [comment]
Yes
This is tested with V2.0.0
I only use the send Email function
And that works perfectly
But I suspect it will work fine for receive email

**Comment by mobizt** [comment]
Ok thanks. I merge it and please test it for me for ethernet.

**Pull request merged**
